/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    static void main() {
        Contador cont = new Contador();

        cont.atribuirValor(5);
        IO.println(cont.obterValor());
        cont.incrementar();
        IO.println(cont.obterValor());
        cont.atribuirValor(-5);
        IO.println(cont.obterValor());
        cont.atribuirValor(0);
        IO.println(cont.obterValor());
    }
}
