/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Doc classUnderTest = new Doc();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
